language: java
jdk:
- oraclejdk8

before_install:
# apt get jq to fill in blank
- sudo apt-get install -y jq

# decrypt secret files
- openssl aes-256-cbc -K $encrypted_7f9b08ce8bbc_key -iv $encrypted_7f9b08ce8bbc_iv -in deploy/secrets.tar.enc -out deploy/secrets.tar -d
- cd deploy && tar xvf secrets.tar && cd ../

# detects version number
- tag=${TRAVIS_COMMIT:0:7}

before_script:
# set up production properties using secret file
- cd deploy && ./setup && cd ../
- gradleSetting=`cat build.gradle`
- versionSetted=${gradleSetting//versionPlaceholder/$tag}
- printf "$versionSetted" > build.gradle
- export PATH=$HOME/google-cloud-sdk/bin:$PATH
- curl -fsS -o $HOME/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
- cd $HOME
- tar -xzf google-cloud-sdk.tar.gz
- ./google-cloud-sdk/install.sh --usage-reporting false --path-update false --command-completion false
- cd $TRAVIS_BUILD_DIR
- gcloud -q components install app-engine-java

deploy:
  provider: gae
  keyfile: deploy/viz-group1-1931c0ea4ed8.json
  project: viz-group1
  on:
    all_branches: true
