language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mkdir -p config
  - cp deploy/database.yml config/database.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS viz;'

before_script:
  - tag=${TRAVIS_COMMIT:0:7}
